name: Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    name: Deploying to Netlify
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: | 
            cd pingup-react
            npm install
  
      - name: build the project
        run: |
            cd pingup-react
            npm run build
      
      - name: Install Netlify CLI
        run: |
            cd pingup-react
            npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy --dir=pingup-react/dist --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  
